# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20289e867d644aeaf4ec251fca1f481e07990a74c2aa1b5c2fed66d383b78757f03f2891b6f12c94f2160da025adf91da02b9e2ff05d31f7ef3bbce5758a516d

test:
  secret_key_base: 5b30a95ff3893a1be50bce9db3882b075bb6e62cae196b240e684a2c8013439f0c5fa24bc47a9748c70e8e9e35c24226a09677675d52ee99c02a281b1046cc1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
